"""Render the CHECKS registry into GitHub Actions workflows.

Every check becomes its own **job**, not a step. That is deliberate: a GitHub
status-check context is the job name, so one-job-per-check is what makes the
required-status-check list in ``policy.required_contexts`` real, and it gives a
pull request granular red/green instead of a single opaque pass/fail.

The YAML is emitted as text rather than dumped from a dict so the generated file
keeps its comments and ordering — it is meant to be read and committed.
"""

from __future__ import annotations

from pathlib import Path

from codebase_memory.governance.checks import CHECKS, Check, resolve_package
from codebase_memory.governance.policy import CALLER_JOB

WORKFLOW_DIR = ".github/workflows"
STANDALONE_NAME = "quality-gate.yml"
REUSABLE_NAME = "reusable-quality-gate.yml"
DEFAULT_PYTHON = "3.11"

_HEADER = """# Generated by codebase-memory-mcp (scaffold_ci).
# Edit the CHECKS registry in codebase_memory/governance/checks.py and
# regenerate — hand-edits here will drift from the required status checks.
"""

_INSTALL = """      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]" || pip install -e .
"""


def _checkout(fetch_all: bool = False) -> str:
    block = "      - uses: actions/checkout@v4\n"
    if fetch_all:
        block += "        with:\n          fetch-depth: 0\n"
    return block


def _setup_python(version_expr: str) -> str:
    return (
        "      - uses: actions/setup-python@v5\n"
        "        with:\n"
        f"          python-version: {version_expr}\n"
    )


def _job(check: Check, version_expr: str, package: str) -> str:
    """One job per check, named by check id so the context name is stable."""
    if check.id == "graph":
        return _graph_job(check, version_expr)

    cmd = " ".join(check.resolve(package))
    lines = [
        f"  {check.id}:",
        f"    name: {check.id}",
        "    runs-on: ubuntu-latest",
        "    steps:",
        _checkout().rstrip("\n"),
        _setup_python(version_expr).rstrip("\n"),
        _INSTALL.rstrip("\n"),
    ]
    if check.install and check.install != "codebase-memory-mcp":
        lines.append(f"      - name: Install {check.install}\n        run: pip install {check.install}")
    lines.append(f"      - name: {check.description}\n        run: {cmd}")
    return "\n".join(lines) + "\n"


def _graph_job(check: Check, version_expr: str) -> str:
    """The structural gate: pull-request only, and advisory (continue-on-error)."""
    return (
        f"  {check.id}:\n"
        f"    name: {check.id}\n"
        "    # Advisory: blast radius is a heuristic. Promote to blocking only\n"
        "    # after calibrating HIGH_FANIN on real pull requests.\n"
        "    if: github.event_name == 'pull_request'\n"
        "    runs-on: ubuntu-latest\n"
        "    continue-on-error: true\n"
        "    steps:\n"
        f"{_checkout(fetch_all=True)}"
        f"{_setup_python(version_expr)}"
        f"{_INSTALL}"
        "      - name: Fetch base branch\n"
        "        run: git fetch --no-tags origin ${{ github.base_ref }}\n"
        f"      - name: {check.description}\n"
        "        run: codebase-memory-gate --base origin/${{ github.base_ref }}\n"
    )


def _jobs(checks: list[Check], version_expr: str, package: str) -> str:
    return "\n".join(_job(c, version_expr, package) for c in checks)


def render_standalone(
    package: str = ".",
    python_version: str = DEFAULT_PYTHON,
    checks: list[Check] | None = None,
    default_branch: str = "main",
) -> str:
    """A self-contained workflow, for repositories not backed by an org ruleset."""
    selected = checks if checks is not None else list(CHECKS)
    version_expr = f'"{python_version}"'
    return (
        f"{_HEADER}"
        "name: quality-gate\n"
        "\n"
        '"on":\n'  # quoted: YAML 1.1 reads bare `on` as boolean true
        "  pull_request:\n"
        "  push:\n"
        f"    branches: [{default_branch}]\n"
        "\n"
        "permissions:\n"
        "  contents: read\n"
        "\n"
        "jobs:\n"
        f"{_jobs(selected, version_expr, package)}"
    )


def render_reusable(
    package: str = ".",
    python_version: str = DEFAULT_PYTHON,
    checks: list[Check] | None = None,
) -> str:
    """The org-hosted definition every repository calls into.

    Policy is edited once here; every caller inherits the change on its next run.
    """
    selected = checks if checks is not None else list(CHECKS)
    return (
        f"{_HEADER}"
        "name: reusable-quality-gate\n"
        "\n"
        '"on":\n'  # quoted: YAML 1.1 reads bare `on` as boolean true
        "  workflow_call:\n"
        "    inputs:\n"
        "      python-version:\n"
        "        type: string\n"
        "        required: false\n"
        f'        default: "{python_version}"\n'
        "      package:\n"
        "        description: Import package to type-check and scan.\n"
        "        type: string\n"
        "        required: false\n"
        f'        default: "{package}"\n'
        "\n"
        "permissions:\n"
        "  contents: read\n"
        "\n"
        "jobs:\n"
        f"{_jobs(selected, '${{ inputs.python-version }}', package)}"
    )


def render_caller(
    org: str,
    workflow_repo: str = ".github",
    ref: str = "main",
    python_version: str = DEFAULT_PYTHON,
    default_branch: str = "main",
) -> str:
    """The ~12-line per-repo workflow that delegates to the org's definition."""
    return (
        f"{_HEADER}"
        "name: quality-gate\n"
        "\n"
        '"on":\n'  # quoted: YAML 1.1 reads bare `on` as boolean true
        "  pull_request:\n"
        "  push:\n"
        f"    branches: [{default_branch}]\n"
        "\n"
        "jobs:\n"
        f"  {CALLER_JOB}:\n"
        f"    uses: {org}/{workflow_repo}/.github/workflows/{REUSABLE_NAME}@{ref}\n"
        "    with:\n"
        f'      python-version: "{python_version}"\n'
    )


def render(
    root: str | Path,
    mode: str = "reusable",
    org: str | None = None,
    python_version: str = DEFAULT_PYTHON,
    default_branch: str = "main",
) -> tuple[str, str]:
    """Return ``(filename, content)`` for the requested scaffold mode."""
    package = resolve_package(root)
    if mode == "reusable":
        if not org:
            raise ValueError("mode='reusable' requires an 'org' argument")
        return STANDALONE_NAME, render_caller(
            org, python_version=python_version, default_branch=default_branch
        )
    if mode == "standalone":
        return STANDALONE_NAME, render_standalone(
            package, python_version, default_branch=default_branch
        )
    if mode == "publish":  # write the org-side reusable definition itself
        return REUSABLE_NAME, render_reusable(package, python_version)
    raise ValueError(f"Unknown mode {mode!r}; expected reusable, standalone, or publish.")


def write_workflow(root: str | Path, filename: str, content: str, overwrite: bool = False) -> Path:
    """Write ``content`` to ``<root>/.github/workflows/<filename>``."""
    target = Path(root) / WORKFLOW_DIR / filename
    if target.exists() and not overwrite:
        raise FileExistsError(f"{target} already exists; pass overwrite=True to replace it.")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return target
